#!/bin/bash
read -p "enter your first number: " num1
read -p "enter your second number: " num2
echo "Before swapping: num1=$num1 and num2=$num2"
num1=$((num1 + num2))
num2=$((num1 - num2))
num1=$((num1 - num2))
echo "After swapping: num1=$num1 and num2=$num2"
